### ISSUE TITLE
Intrinsic actual argument not declared intrinsic in intrinsic_actual_4.f90

### ISSUE THREAD

**Issue by nncarlson** [nncarlson/gfortran.dg#9]
The LEN intrinsic function is passed as an actual argument to a procedure. This requires that LEN be explicitly declared INTRINSIC (see F08 section 5.3.11, par 2), but this is not done.

Here's the NAG error message:
```
$ nagfor -kind=byte intrinsic_actual_4.f90
NAG Fortran Compiler Release 6.1(Tozai) Build 6144
Error: intrinsic_actual_4.f90, line 17: Actual INTRINSIC procedure argument LEN not declared INTRINSIC
```

**Comment by janusw** [comment]
Fixed in https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=257364
